"""Wingman's own changelog: curated, merged-PR titles (RFC-038, issue #145).

Source of truth is `src/wingman/changelog_data.py`, a committed static
module regenerated by `scripts/generate_changelog.py` at release time — NOT
a live `git log` read. The running process (installed via `uv tool install`,
per docs/INSTALL.md) has no `.git` directory to read: `uv tool install`
builds a wheel into an isolated tool venv even for the "install from a local
checkout" path, verified empirically against a real installed instance
(nothing under the tool's site-packages carries VCS history). A generated
file that ships as ordinary package source is the only option that works
across every documented install path (git URL, local checkout, PyPI-style
wheel). See RFC-038 for the full trade-off.

Titles render verbatim — no model rewrite (issue #145 scope). The
user-facing filter below is a deliberately loose, deterministic heuristic:
only titles that unambiguously read as internal repo/process bookkeeping
are excluded, per the issue's own "when in doubt, include" instruction.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import date as date_cls
from datetime import timedelta


@dataclass(frozen=True)
class ChangelogEntry:
    date: str  # ISO "YYYY-MM-DD" — the merge commit's date, our PR-merge-date proxy
    pr: int
    title: str


# Shared by the web UI tab and the MCP tool so both surfaces show the same
# horizon — long enough to cover "what's happened lately", short enough that
# neither surface has to render this repo's entire history.
DEFAULT_DISPLAY_LIMIT = 60


# Deliberately small and specific: each pattern targets a category the repo's
# own history actually produces (see scripts/generate_changelog.py's sample),
# not a broad guess at what "internal" might mean. A missed internal title
# just shows up in the list; a wrongly-excluded user-facing one hides a real
# change — the issue's stated preference is to err toward the former.
_INTERNAL_TITLE_PATTERNS = (
    re.compile(r"\bsession (snapshot|context)\b", re.IGNORECASE),  # repo-continuity notes
    re.compile(r"^address review:", re.IGNORECASE),  # code-review-remediation follow-ups
    re.compile(r"^(chore|test|tests|ci|internal)\s*:", re.IGNORECASE),
    re.compile(r"\btest[- ]only\b", re.IGNORECASE),
    re.compile(r"\badmin\b.{0,40}\bfix", re.IGNORECASE),  # admin-page-only bugfixes
)


def is_user_facing(title: str) -> bool:
    """True unless the title unambiguously reads as internal-only."""
    return not any(pattern.search(title) for pattern in _INTERNAL_TITLE_PATTERNS)


def load_entries() -> list[ChangelogEntry]:
    """Every generated entry, in the data file's own order."""
    from wingman.changelog_data import CHANGELOG_DATA

    return [ChangelogEntry(date=date, pr=pr, title=title) for date, pr, title in CHANGELOG_DATA]


def user_facing_entries() -> list[ChangelogEntry]:
    """Curated entries, newest first."""
    entries = [entry for entry in load_entries() if is_user_facing(entry.title)]
    return sorted(entries, key=lambda entry: entry.date, reverse=True)


def counts_today_and_week(entries: list[ChangelogEntry], today: date_cls) -> tuple[int, int]:
    """(# dated today, # dated within the trailing 7-day window including today)."""
    window_start = today - timedelta(days=6)
    today_iso = today.isoformat()
    window_start_iso = window_start.isoformat()
    today_count = sum(1 for entry in entries if entry.date == today_iso)
    week_count = sum(1 for entry in entries if window_start_iso <= entry.date <= today_iso)
    return today_count, week_count


def render_changelog(today: date_cls) -> str:
    """Plain-text rendering shared by the MCP tool and the CLI: today/week
    counts up front, then curated entries newest first, capped at
    DEFAULT_DISPLAY_LIMIT."""
    entries = user_facing_entries()
    if not entries:
        return "No changelog entries."
    today_count, week_count = counts_today_and_week(entries, today)
    lines = [f"Changelog — {today_count} new today, {week_count} in the last 7 days.", ""]
    lines.extend(
        f"- {entry.date} {entry.title} (#{entry.pr})" for entry in entries[:DEFAULT_DISPLAY_LIMIT]
    )
    if len(entries) > DEFAULT_DISPLAY_LIMIT:
        lines.append("- …older entries omitted")
    return "\n".join(lines)
