export type Question = "Start here" | "Who do I talk to?" | "Why this conversation?" | "What do we talk about?";
export type GuideStep = { title: string; body: string; prompt: string; proof: string; note?: string };
export type Prerequisite = { slug: string; label: string };
export type Guide = {
  slug: string; title: string; summary: string; ask: string; intro: string;
  question: Question; prerequisites: Prerequisite[]; steps: GuideStep[];
  nextSlug: string; nextQuestion: Question;
};

const connected: Prerequisite[] = [
  { slug: "hosted-setup", label: "Hosted setup" },
  { slug: "local-setup", label: "Local setup" },
];

export const guides: Guide[] = [
  {slug:"hosted-setup",title:"Get set up when someone is hosting for you",summary:"Two private links, no software, no terminal, no API keys.",ask:"I was handed two Wingman links. What do I do with them?",intro:"One link connects Claude to Wingman. The other opens your private page. Treat both like passwords; your host has handled the software and model setup.",question:"Start here",prerequisites:[],nextSlug:"add-cv-linkedin",nextQuestion:"What do we talk about?",steps:[
    {title:"Connect Claude",body:"Open Settings → Connectors → Add custom connector and paste the link ending in /mcp/…. Do not paste that link anywhere public.",prompt:"What do you know about me?",proof:"Wingman answers, even if the honest answer is that it knows nothing yet.",note:"The connector link is a bearer credential. Ask your host to rotate it if it appears in a screenshot or public document."},
    {title:"Open your private page",body:"Use the second link for uploads, today’s digest, and finished reports. It is for glancing and files; the conversation is where you ask Wingman to work.",prompt:"Show me the latest digest and tell me what each section contains.",proof:"Claude can name the latest digest, or tells you plainly that none exists yet."},
    {title:"Check the connection",body:"Ask for workspace status before adding private documents. This separates a connection problem from an empty workspace.",prompt:"Check my Wingman workspace and tell me which capabilities are ready.",proof:"You get a visible ready, missing, or skipped result for each relevant capability."},
  ]},
  {slug:"local-setup",title:"Get set up on your own machine",summary:"Create a private local workspace and connect Claude.",ask:"Help me set up Wingman on my own machine.",intro:"This path is for the person operating their own instance. Your database, inbox, and reports stay in your local workspace.",question:"Start here",prerequisites:[],nextSlug:"add-cv-linkedin",nextQuestion:"What do we talk about?",steps:[
    {title:"Install and check the workspace",body:"Follow the current installation guide, initialise a workspace, then run Wingman’s doctor check.",prompt:"Check my Wingman workspace and explain anything that is not ready.",proof:"Doctor reports the active workspace and says which capabilities will work or degrade."},
    {title:"Choose the providers you need",body:"Model-powered extraction and judgment need a configured model provider. Semantic similarity can use a provider or the keyless local hashed option.",prompt:"Which Wingman capabilities work with the providers I have configured?",proof:"The answer separates local, keyless work from steps that need a paid provider.",note:"Set API keys in the terminal or an approved credential store. Never send a key through the model conversation."},
    {title:"Connect Claude",body:"Add the local MCP server to your Claude client, then verify status before importing private data.",prompt:"What do you know about me?",proof:"Claude reaches the local workspace and answers, even if the workspace is empty."},
  ]},
  {slug:"research-a-company",title:"Research a company before a conversation",summary:"Turn approved public sources into a dated, inspectable dossier.",ask:"Give me the current picture on this company.",intro:"Wingman researches sources you approve, keeps facts distinct from inference, and reports change without presenting a stale snapshot as current.",question:"Who do I talk to?",prerequisites:connected,nextSlug:"warm-introduction",nextQuestion:"Who do I talk to?",steps:[
    {title:"Name the company",body:"Give Wingman the company name and its public site so the target is unambiguous.",prompt:"Follow Acme at https://example.com.",proof:"The company appears in the followed list with its declared source."},
    {title:"Approve the useful sources",body:"Add the careers page, newsroom, blog, or other public pages that should be read. Research stays within that declared scope.",prompt:"Show me Acme’s sources and add its careers and newsroom pages after I approve them.",proof:"Wingman lists the exact URLs it may fetch before research runs."},
    {title:"Build the dossier",body:"Refresh the approved sources and ask for the dated company view.",prompt:"Give me the current picture on this company.",proof:"The dossier separates facts from inference, links its sources, and marks anything stale."},
  ]},
  {slug:"warm-introduction",title:"Find a warm introduction",summary:"See the real signals behind a relationship — no invented familiarity.",ask:"Who could credibly open a door here?",intro:"Wingman can surface people in your imported network and explain the signals it has. It will not imply closeness or a referral the record cannot support.",question:"Who do I talk to?",prerequisites:[{slug:"add-cv-linkedin",label:"LinkedIn connections imported"}],nextSlug:"meeting-brief",nextQuestion:"What do we talk about?",steps:[
    {title:"Name the target",body:"Say which company or person matters. Ask for the relationship evidence, not a list of names.",prompt:"Who could credibly open a door here?",proof:"Each candidate is accompanied by the real connection signals Wingman has."},
    {title:"Inspect the warmth components",body:"Treat warmth as an auditable signal vector, not a promise that someone will help.",prompt:"Show me the evidence behind each warmth signal for this person.",proof:"You can distinguish an imported connection from an interaction, shared work, or a stronger relationship."},
    {title:"Prepare the request",body:"Ask for cited talking points and intro bullets. Compose and send the message yourself.",prompt:"Prepare the raw material for an introduction request, with no invented familiarity.",proof:"You receive bullets tied to real evidence and no message is sent."},
  ]},
  {slug:"morning-digest",title:"Understand what arrived in your digest",summary:"See what changed, why it matters, and stop recurring noise.",ask:"Walk me through this morning’s digest.",intro:"An overnight run refreshes the people and companies you explicitly follow and writes a dated digest. It does not apply, message, or act while you sleep.",question:"Who do I talk to?",prerequisites:[{slug:"research-a-company",label:"A followed company or person"}],nextSlug:"research-a-company",nextQuestion:"Who do I talk to?",steps:[
    {title:"Separate new from carried forward",body:"Start with new writing, news, research-page changes, and job signals.",prompt:"Walk me through this morning’s digest.",proof:"Wingman names the date and separates new signals from older open actions.",note:"Wingman ships no scheduler. The overnight run happens only because you or your host scheduled it."},
    {title:"Open the evidence",body:"Each action should say what changed, why it matters, who it concerns, and the source behind it.",prompt:"Show me the source behind each action before we decide what to keep.",proof:"Every consequential action resolves to a stored source or is marked unsupported."},
    {title:"Triage every action",body:"Keep useful actions, mute recurring noise, or snooze something until it can matter.",prompt:"Help me triage every action: keep, mute, or snooze.",proof:"Muted items stop recurring and snoozed items carry a visible return date."},
  ]},
  {slug:"capture-links",title:"Deal with a pile of links you can’t sort",summary:"Capture first, keep provenance, and triage when your attention returns.",ask:"Put these links somewhere I can sort later.",intro:"The heap is a low-friction inbox for leads and references that feel useful but do not deserve a decision now.",question:"Who do I talk to?",prerequisites:connected,nextSlug:"research-a-company",nextQuestion:"Who do I talk to?",steps:[
    {title:"Capture the real links",body:"Send the URLs with one line about why they caught your attention.",prompt:"Put these links somewhere I can sort later.",proof:"Each item appears with its original URL and capture context."},
    {title:"Add a rough heat",body:"Use a lightweight priority signal as a sorting aid, not a permanent judgment.",prompt:"Show me the uncategorised links and help me give each one a rough heat.",proof:"The heap sorts by heat without changing the source or inventing a conclusion."},
    {title:"Triage when attention returns",body:"Decide which items become a company, person, opportunity, or approved research source.",prompt:"Show me the hottest items and help me decide where each one belongs.",proof:"Promoted items retain their original source and the rest stay parked."},
  ]},
  {slug:"job-criteria",title:"Tell it what kind of job you want",summary:"Turn preferences, hard limits, and anti-signals into visible criteria.",ask:"Help me define what a good next role looks like.",intro:"Criteria turn a stream of openings into a ranked decision. Without them, openings arrive unscored.",question:"Why this conversation?",prerequisites:connected,nextSlug:"assess-a-role",nextQuestion:"Why this conversation?",steps:[
    {title:"Do the criteria interview",body:"Name hard filters, plausible role shapes, weighted wants, anti-signals, and the trade-offs between good options.",prompt:"Help me define what a good next role looks like.",proof:"Wingman asks about all five areas rather than inferring them from a title."},
    {title:"Read the document",body:"The output is human-readable. Change anything generic before it is used to judge a role.",prompt:"Show me my job criteria document and explain every hard filter and weight.",proof:"You can read and edit the criteria behind the score."},
    {title:"Use real verdicts to improve it",body:"Accepted and rejected roles can support proposed changes. Wingman will not apply those changes automatically.",prompt:"Compare my recent role verdicts with my criteria and propose changes for me to review.",proof:"Every proposed edit is shown before the criteria document changes."},
  ]},
  {slug:"assess-a-role",title:"Work out whether a posting is worth your time",summary:"See met, partial, gap, and unknown — each with evidence.",ask:"Does this job fit me?",intro:"Paste a posting or share its public URL. Wingman compares each requirement with your profile and leaves missing evidence as unknown.",question:"Why this conversation?",prerequisites:[{slug:"add-cv-linkedin",label:"A cited profile"},{slug:"job-criteria",label:"Job criteria"}],nextSlug:"research-a-company",nextQuestion:"Who do I talk to?",steps:[
    {title:"Give it the full posting",body:"Use the real description, not a summary. Save the page to a file if a login wall or script-only site blocks the URL.",prompt:"Does this job fit me?",proof:"Wingman extracts the requirements with quotes from the posting."},
    {title:"Read the gaps first",body:"Inspect each met, partial, gap, and unknown verdict and open the profile evidence behind it.",prompt:"Walk me through the gaps and unknowns before the overall fit.",proof:"Every supported verdict carries a real profile item; gaps and unknowns remain visible."},
    {title:"Build a pack if the role earns one",body:"The pack combines the cited fit summary, your evidence, and company intelligence already in the workspace.",prompt:"Build an application pack for this role using only evidence already in my workspace.",proof:"You receive raw material with citations. No application is submitted and no final letter is invented."},
  ]},
  {slug:"fix-my-profile",title:"Fix something it got wrong about you",summary:"Inspect the source, remove a bad claim, or choose between conflicts.",ask:"That’s wrong about me. Fix it and show me what changes.",intro:"Corrections are part of the record. Wingman keeps provenance and never silently overwrites contradictory sources.",question:"Why this conversation?",prerequisites:[{slug:"add-cv-linkedin",label:"A cited profile"}],nextSlug:"assess-a-role",nextQuestion:"Why this conversation?",steps:[
    {title:"Name the claim",body:"Say what is wrong and ask to see the source that produced it.",prompt:"That’s wrong about me. Show me the evidence behind it.",proof:"Wingman displays the item identifier and source rather than defending the claim."},
    {title:"Choose the truthful action",body:"Remove an unsupported item, resolve competing versions, or re-ingest the corrected source document.",prompt:"Remove this unsupported item and show me any conflicts that remain.",proof:"The mutation is explicit and the contradictory data is not silently overwritten."},
    {title:"Verify the profile",body:"Render the profile again. Rerun older assessments when they cite superseded items.",prompt:"Show me my updated profile and name any assessments I should rerun.",proof:"The bad claim is absent or superseded and the new profile retains its source lineage."},
  ]},
  {slug:"add-cv-linkedin",title:"Add your CV and LinkedIn",summary:"Build a cited profile from the documents that already know you.",ask:"Add my CV and LinkedIn export to my profile.",intro:"Give Wingman the source files, not a summary. It extracts roles, achievements, skills, and testimonials with the original wording attached.",question:"What do we talk about?",prerequisites:connected,nextSlug:"fix-my-profile",nextQuestion:"Why this conversation?",steps:[
    {title:"Add your source-of-truth CV",body:"Upload the document you maintain. PDF, DOCX, Markdown, LaTeX, plain text, and accessible Google document links are supported.",prompt:"Add my CV to my profile and report anything you could not support.",proof:"Each accepted role, skill, and achievement points to a real sentence in the document."},
    {title:"Add the LinkedIn export",body:"The export can add positions, skills, recommendations, and names from your connections. Email addresses are not stored.",prompt:"Add my LinkedIn export and tell me what it contributes beyond my CV.",proof:"New evidence and connections are listed separately from claims already supported by the CV."},
    {title:"Review the result",body:"Inspect conflicts and anything surprising before using the profile to judge a role.",prompt:"Show me the profile you built, including conflicts and unsupported proposals.",proof:"The rendered profile exposes its sources and leaves contradictions side by side."},
  ]},
  {slug:"meeting-brief",title:"Prepare for a meeting with a specific person",summary:"Bring together their point of view, your overlap, background, and news.",ask:"Prepare me for my conversation with Jane.",intro:"A person brief connects what they have written with evidence from your work, then gives you raw material for the conversation.",question:"What do we talk about?",prerequisites:[{slug:"research-a-company",label:"Current public sources"},{slug:"add-cv-linkedin",label:"Your cited profile"}],nextSlug:"warm-introduction",nextQuestion:"Who do I talk to?",steps:[
    {title:"Refresh what is current",body:"Fetch only the public sources already attached and ask for recent news if it matters to the meeting.",prompt:"Refresh what we know about Jane from the public sources I approved.",proof:"New material is dated and attributed; failed sources keep their previous snapshot and report the failure."},
    {title:"Build the brief",body:"Bring together their point of view, your relevant evidence, relationship background, and recent developments.",prompt:"Prepare me for my conversation with Jane.",proof:"Every stance and overlap resolves to a quote from their writing or yours."},
    {title:"Make the one-glance version",body:"Export the briefing dock when you want something beside you during the meeting.",prompt:"Export a one-glance briefing dock for this meeting.",proof:"The output has brief, point of view, background, and news sections with clickable sources."},
  ]},
  {slug:"answer-bank",title:"Answer the same application question again",summary:"Recall refined answers without pretending every application is identical.",ask:"Have I answered a question like this before?",intro:"The answer bank stores the question, your refined answer, and its context so real work can be reused without submitting a generic response blindly.",question:"What do we talk about?",prerequisites:connected,nextSlug:"assess-a-role",nextQuestion:"Why this conversation?",steps:[
    {title:"Search by meaning",body:"Ask for similar confirmed answers rather than relying on exact wording.",prompt:"Have I answered a question like this before?",proof:"Wingman returns relevant confirmed answers with their original questions and context."},
    {title:"Adapt it to this role",body:"Review the old context and update claims, names, and emphasis for the current application.",prompt:"Show me what must change before this answer fits the current role.",proof:"The reused evidence remains visible and role-specific changes are identified."},
    {title:"Confirm the version you stand behind",body:"Only a reviewed answer should become part of the bank for later recall.",prompt:"Save this as my confirmed answer with the current application context.",proof:"The answer appears in later searches as confirmed, with its context attached."},
  ]},
];

export const guideGroups: { label: Question; slugs: string[] }[] = [
  {label:"Start here",slugs:["hosted-setup","local-setup"]},
  {label:"Who do I talk to?",slugs:["research-a-company","warm-introduction","morning-digest","capture-links"]},
  {label:"Why this conversation?",slugs:["job-criteria","assess-a-role","fix-my-profile"]},
  {label:"What do we talk about?",slugs:["add-cv-linkedin","meeting-brief","answer-bank"]},
];

export function getGuide(slug:string){ return guides.find((guide)=>guide.slug===slug); }
