"""A completed interview form, ingested into one named tenant's workspace (#287).

The generator half emits an Apps Script and a manifest keyed by question
TITLE (application/interview_form.py) — title, because that is the only
thing a Google Forms response export carries back. This half reads the
export, routes each answer by that manifest, and writes it into the
workspace of the tenant the OPERATOR named.

Three things about this are deliberate and load-bearing.

**It is an operator act, so it is CLI-only.** The person who exports the
responses lands them in somebody ELSE'S workspace. A tenant's MCP session
is bound to that tenant's own Config, and a tool that wrote across
workspaces would be a hole in exactly the isolation #333 closed for
carve-off — so there is no MCP tool here, and the gate is shell access to
the box, the same gate `tenant urls` and `tenant answers` sit behind. The
target is named explicitly (`wingman tenant ingest-form <slug> <file>`)
and never inferred from the file: a response export carries whatever the
form's own bearer URL collected, and trusting it to say whose answers
these are would attribute one person's words to another.

**Nothing is written before it is shown.** `plan_ingest` is pure: it
parses, routes, assembles, and reports, touching no database and no file.
`apply_plan` is the only writer. The failure being designed against is
writing into another person's career record unprompted — RFC-025's
confirmation gate and `wingman-migrate-tenant.sh`'s dry-run default, in
the one place where the writer and the subject are different people.

**The answers ARE evidence, unlike a question-of-the-day answer
(RFC-067).** The distinction is who wrote the question. A QOTD question is
authored by the operator, so a citable answer would let a leading question
write sentences into somebody's career record — which is why it is inert.
A form answer responds to WINGMAN'S OWN interview questions: RFC-035's
five criteria areas and the standard nomination subtypes, the same content
`interview_react` and `job_criteria` capture in conversation, just
asynchronously. So it is captured the ordinary way, through the same
application functions the conversational path calls
(`capture_interview_reaction`, `capture_qa`, `save_criteria`) — never a
second write path, which would drift from their validation rules the first
time one of them changed. What differs is provenance only: every capture
records that it arrived via a form ingested by an operator (`via_form`),
because somebody reading their own profile a year later should be able to
tell which answers they wrote in a form months ago from the ones they said
out loud.
"""

from __future__ import annotations

import csv
import io
import json
import re
from datetime import UTC, datetime
from pathlib import Path

from pydantic import BaseModel, Field

from wingman.application.evidence import canonical_punctuation, fold_whitespace
from wingman.application.ingest import IngestError
from wingman.application.interview_form import Destination, FormQuestion, form_questions
from wingman.domain.provenance import FORM_ARRIVAL
from wingman.infrastructure.config import Config
from wingman.infrastructure.logs import get_logger
from wingman.infrastructure.storage import Storage

_logger = get_logger("application.form_ingest")

#: Google Forms' own first column. Used for the submission time and never
#: routed anywhere, so it is not reported as an unknown question.
TIMESTAMP_COLUMN = "timestamp"


def _match_key(title: str) -> str:
    """The key a question title is matched on: whitespace folded, dashes and
    quotes canonicalised, case ignored.

    Exact string equality would be defensible — the manifest and the form
    were generated by the same code — but a response export makes a round
    trip through Forms and, often, a spreadsheet, and an em dash that comes
    back as an en dash would silently unroute every nomination question.
    Folding presentation only keeps the match deterministic (no model, no
    fuzzy scoring) while surviving the trip.
    """
    return canonical_punctuation(fold_whitespace(title)).casefold()


class FormResponse(BaseModel):
    """One submission: the answers as the export carries them, verbatim."""

    submitted_at: str = ""
    answers: dict[str, str] = Field(default_factory=dict)


def _rows_from_csv(text: str) -> list[dict[str, str]]:
    reader = csv.reader(io.StringIO(text))
    try:
        header = next(reader)
    except StopIteration:
        return []
    rows: list[dict[str, str]] = []
    for cells in reader:
        if not any(cell.strip() for cell in cells):
            continue
        row = {name: "" for name in header}
        for name, cell in zip(header, cells, strict=False):
            row[name] = cell
        rows.append(row)
    return rows


def _rows_from_json(text: str) -> list[dict[str, str]]:
    try:
        payload = json.loads(text)
    except json.JSONDecodeError as exc:
        raise IngestError(f"the responses file is not valid JSON ({exc}). Nothing was read.")
    if isinstance(payload, dict):
        inner = payload.get("responses")
        entries = inner if isinstance(inner, list) else [payload]
    elif isinstance(payload, list):
        entries = payload
    else:
        raise IngestError(
            "the responses JSON must be an object of answers, a list of them, or "
            "{'responses': [...]}. Nothing was read."
        )
    rows: list[dict[str, str]] = []
    for entry in entries:
        if not isinstance(entry, dict):
            raise IngestError("every response in the JSON must be an object of title -> answer.")
        rows.append({str(key): "" if value is None else str(value) for key, value in entry.items()})
    return rows


def parse_responses(path: Path) -> list[FormResponse]:
    """Every submission in a Forms response export, oldest first.

    CSV is what "Download responses" gives you and is the expected input;
    JSON is accepted because an export that has been through any tooling at
    all tends to arrive that way, and refusing it would push the operator
    into hand-converting a file — the step most likely to alter somebody's
    words on the way in.
    """
    suffix = path.suffix.lower()
    if suffix not in (".csv", ".json"):
        raise IngestError(
            f"{path.name} is neither a .csv nor a .json responses export. Nothing was read."
        )
    try:
        # utf-8-sig: a Forms CSV opened and re-saved by a spreadsheet carries
        # a BOM, which would otherwise become part of the first column's name
        # and unroute it.
        text = path.read_text(encoding="utf-8-sig")
    except OSError as exc:
        raise IngestError(f"could not read {path} ({exc}). Nothing was read.") from exc
    except UnicodeDecodeError as exc:
        raise IngestError(f"{path.name} is not UTF-8 text ({exc}). Nothing was read.") from exc
    rows = _rows_from_csv(text) if suffix == ".csv" else _rows_from_json(text)
    responses: list[FormResponse] = []
    for row in rows:
        submitted = ""
        answers: dict[str, str] = {}
        for title, value in row.items():
            if _match_key(title) == TIMESTAMP_COLUMN:
                submitted = value.strip()
                continue
            answers[title] = value
        responses.append(FormResponse(submitted_at=submitted, answers=answers))
    if not responses:
        raise IngestError(f"{path.name} has no submissions in it. Nothing was read.")
    return responses


def questions_from_manifest(text: str) -> list[FormQuestion]:
    """The routing table a `wingman tenant form` run wrote, read back.

    The default is the CURRENT question set, since the form was generated
    from this same code. A manifest is for the case that stops being true —
    an older form still out with somebody, or one the owner edited — where
    the honest answer is to route against the table that form was built
    from rather than to assume the questions never changed.
    """
    try:
        payload = json.loads(text)
    except json.JSONDecodeError as exc:
        raise IngestError(f"the manifest is not valid JSON ({exc}).") from exc
    if not isinstance(payload, dict) or not isinstance(payload.get("questions"), list):
        raise IngestError("the manifest has no 'questions' list — is it a form manifest?")
    questions: list[FormQuestion] = []
    for entry in payload["questions"]:
        if not isinstance(entry, dict):
            raise IngestError("every manifest question must be an object.")
        try:
            questions.append(FormQuestion(**entry))
        except Exception as exc:  # pydantic validation — the manifest is data, not code
            raise IngestError(f"a manifest question is malformed: {exc}") from exc
    if not questions:
        raise IngestError("the manifest lists no questions.")
    return questions


class PlannedCapture(BaseModel):
    """One answer, routed — what apply_plan will write, and nothing more."""

    title: str
    destination: Destination
    subtype: str = ""
    #: Nomination captures only: the person/organization named.
    target: str = ""
    #: The evidence quote — the person's own 'why', verbatim.
    why: str = ""
    #: mission_alignment_* only: what they understand the org's purpose to be.
    primary_purpose: str = ""
    #: The whole answer, for the destinations that store one (answer bank,
    #: and a profile question with no nomination subtype).
    answer: str = ""


class SkippedAnswer(BaseModel):
    """Something the form carried that will NOT be written, and why.

    Every one of these is printed. An answer that is silently dropped is
    worse than one that is refused: the operator believes it landed, and
    the person who wrote it never finds out that it did not.
    """

    what: str
    reason: str


class IngestPlan(BaseModel):
    """Everything a run would do, computed without writing anything."""

    slug: str
    source: str
    submitted_at: str = ""
    submission_index: int = 1
    submission_count: int = 1
    captures: list[PlannedCapture] = Field(default_factory=list)
    #: (heading, verbatim answer) per answered criteria area, in form order.
    criteria_areas: list[tuple[str, str]] = Field(default_factory=list)
    criteria_blank: list[str] = Field(default_factory=list)
    criteria_document: str = ""
    skipped: list[SkippedAnswer] = Field(default_factory=list)

    @property
    def writes_anything(self) -> bool:
        return bool(self.captures or self.criteria_document)


# Bullets and numbering a person naturally types in front of a list item.
# Stripped before the separator search so "- Ada Lovelace — why" parses the
# same as "Ada Lovelace — why"; the form asks for one per line, not for a
# particular punctuation.
_BULLET = re.compile(r"^\s*(?:[-*•·]|\(?\d+[.)])\s+")

# Separator kinds, in preference order. A dash is tried before a colon
# because a network_admired answer is asked to carry a LinkedIn URL, and
# "https://..." contains a colon that would otherwise win by position and
# split the line inside the scheme.
_SEPARATORS = ("—", "–", " -- ", " - ", ": ")


def _split_nomination(line: str, parts: int) -> list[str]:
    """A nomination line split into at most `parts` segments, deterministically.

    One separator KIND is chosen — the first of _SEPARATORS present anywhere
    in the line — and the line is split on its first occurrences. Choosing
    the kind before the position is what keeps a URL intact; splitting on
    the earliest character of any kind would cut "https://..." in two.
    """
    for separator in _SEPARATORS:
        if separator in line:
            segments = [part.strip() for part in line.split(separator, parts - 1)]
            return [segment for segment in segments if segment]
    return [line.strip()] if line.strip() else []


def _criteria_heading(question: FormQuestion) -> str:
    """The heading one criteria answer sits under in the assembled document.

    The generator titles these "Job criteria — Hard filters", so the area
    name is the tail. A manifest whose titles were edited keeps the whole
    title as the heading rather than guessing at a structure it no longer
    has.
    """
    _prefix, dash, tail = question.title.partition("—")
    return tail.strip() if dash and tail.strip() else question.title.strip()


def compose_criteria_document(
    slug: str,
    areas: list[tuple[str, str]],
    blank: list[str],
    submitted_at: str,
    today: str,
) -> str:
    """The five criteria answers, assembled into the ONE document RFC-035 stores.

    `job_criteria` keeps a single Markdown document, not five fields, so
    something has to turn five answers into one — and it is done here,
    deterministically, by putting each answer verbatim under the heading of
    the question that asked for it. A model was NOT used, and that is the
    point rather than an economy: RFC-035 makes this document the only
    authority on what the person cares about and says it is their own
    words, so a summarised or smoothed version would be wingman's opinion
    of their criteria, scoring every opening they see against wording they
    never wrote. AGENTS.md forbids a model for file routing and exact
    matching for the same reason.

    The header states where the words came from, because this destination
    is a flat file with no provenance record of its own — the two other
    destinations get theirs from the capture layer. Blank areas are named
    in the header and absent from the body: an empty "## Anti-signals"
    heading reads to the judge as "no anti-signals", which is a claim the
    person never made.
    """
    if not areas:
        return ""
    lines = [f"# Job criteria — {slug}", ""]
    submitted = f" (submitted {submitted_at})" if submitted_at else ""
    provenance = (
        f"These are {slug}'s own words, verbatim, from {FORM_ARRIVAL}"
        f"{submitted} on {today}. Each heading is the question that asked for them; "
        "wingman wrote, reworded and summarised none of it."
    )
    if blank:
        provenance += f" Left blank in the form, and so absent here: {', '.join(blank)}."
    lines += [provenance, ""]
    for heading, answer in areas:
        lines += [f"## {heading}", "", answer.strip(), ""]
    return "\n".join(lines).strip() + "\n"


def choose_submission(responses: list[FormResponse], submission: int | None = None) -> int:
    """Which submission in the export is the person's current answer (0-based).

    A half-filled form is obvious — a blank answer is skipped. A form filled
    TWICE is not, and the two plausible readings differ: merge both, or take
    the later one. Merging is wrong. A second submission is somebody
    redoing the form, and merging leaves the answers they abandoned active
    alongside the ones they replaced — different people named under the
    same subtype, all citable, with nothing recording that one set was
    withdrawn. RFC-028 supersession only fires for the same target, so it
    cannot clean that up. So the LAST submission in the file wins, the
    earlier ones are reported rather than silently ignored, and
    `--submission N` exists for the case the operator knows the last one
    was the mistake.
    """
    if not responses:
        raise IngestError("there are no submissions to ingest.")
    if submission is None:
        return len(responses) - 1
    if submission < 1 or submission > len(responses):
        raise IngestError(
            f"--submission {submission} is out of range: this file has "
            f"{len(responses)} submission(s), numbered 1 (oldest) to {len(responses)}."
        )
    return submission - 1


def plan_ingest(
    slug: str,
    responses: list[FormResponse],
    source: str,
    questions: list[FormQuestion] | None = None,
    submission: int | None = None,
    today: str | None = None,
) -> IngestPlan:
    """Route one submission by title, and assemble what would be written.

    Pure: reads no workspace, writes nothing. Everything a preview needs is
    on the returned plan, so the thing shown to the operator and the thing
    applied are computed once, from the same code, and cannot disagree.
    """
    questions = form_questions() if questions is None else questions
    index = choose_submission(responses, submission)
    response = responses[index]
    by_title = {_match_key(question.title): question for question in questions}
    plan = IngestPlan(
        slug=slug,
        source=source,
        submitted_at=response.submitted_at,
        submission_index=index + 1,
        submission_count=len(responses),
    )
    for older in range(len(responses)):
        if older == index:
            continue
        when = responses[older].submitted_at or f"submission {older + 1}"
        plan.skipped.append(
            SkippedAnswer(
                what=f"submission {older + 1} of {len(responses)} ({when})",
                reason="a later submission in this file is their current answer",
            )
        )
    for title, raw in response.answers.items():
        answer = raw.strip()
        question = by_title.get(_match_key(title))
        if question is None:
            plan.skipped.append(
                SkippedAnswer(
                    what=f"column {title!r}",
                    reason="no question with this title in the form manifest — nothing "
                    "in wingman knows where its answer belongs",
                )
            )
            continue
        if not answer:
            # A blank is the commonest thing in a real form and it is not an
            # error: every question was optional by design. Capturing it
            # would file an empty quote as evidence, which is a claim that
            # they answered.
            plan.skipped.append(SkippedAnswer(what=question.title, reason="left blank in the form"))
            if question.destination == "criteria":
                plan.criteria_blank.append(_criteria_heading(question))
            continue
        if question.destination == "criteria":
            plan.criteria_areas.append((_criteria_heading(question), answer))
        elif question.subtype:
            _plan_nominations(plan, question, answer)
        else:
            plan.captures.append(
                PlannedCapture(
                    title=question.title,
                    destination=question.destination,
                    answer=answer,
                )
            )
    plan.criteria_document = compose_criteria_document(
        slug,
        plan.criteria_areas,
        plan.criteria_blank,
        plan.submitted_at,
        today or datetime.now(UTC).date().isoformat(),
    )
    return plan


def _plan_nominations(plan: IngestPlan, question: FormQuestion, answer: str) -> None:
    """One nomination answer — one per line — split into (target, why).

    The form asks for a name and a reason on each line; the split is
    deterministic (see _split_nomination) because routing and parsing are
    exactly the work AGENTS.md forbids a model for. A line that does not
    carry both is reported with its own text rather than captured half-way:
    'why' is the only thing that ever becomes evidence in an interview
    capture, so a line with no 'why' has nothing to cite, and inventing one
    would be the paraphrase this whole path exists to avoid.
    """
    from wingman.application.interview import MISSION_ALIGNMENT_SUBTYPES

    wants_purpose = question.subtype in MISSION_ALIGNMENT_SUBTYPES
    for number, raw_line in enumerate(answer.splitlines(), start=1):
        line = _BULLET.sub("", raw_line).strip()
        if not line:
            continue
        segments = _split_nomination(line, 3 if wants_purpose else 2)
        where = f"{question.subtype}, line {number}: {line[:60]}"
        if len(segments) < 2:
            plan.skipped.append(
                SkippedAnswer(
                    what=where,
                    reason="no separator between the name and the reason — a nomination "
                    "needs both (write 'Name — why')",
                )
            )
            continue
        if wants_purpose and len(segments) < 3:
            plan.skipped.append(
                SkippedAnswer(
                    what=where,
                    reason="the organization and its purpose are here but no reason — "
                    "'why' is the only thing an interview capture stores as evidence, "
                    "and wingman will not write one (write 'Org — purpose — why')",
                )
            )
            continue
        plan.captures.append(
            PlannedCapture(
                title=question.title,
                destination=question.destination,
                subtype=question.subtype,
                target=segments[0],
                primary_purpose=segments[1] if wants_purpose else "",
                why=segments[2] if wants_purpose else segments[1],
            )
        )


class IngestOutcome(BaseModel):
    """What a run actually wrote — reported per capture, never as a total.

    Partial success is the normal case here (one malformed line among
    twenty good ones), and AGENTS.md is explicit that partial work is
    preserved and failures explain themselves. So one refused capture never
    aborts the rest, and every refusal keeps the reason the application
    function gave.
    """

    written: list[str] = Field(default_factory=list)
    failed: list[SkippedAnswer] = Field(default_factory=list)
    criteria_path: str = ""
    criteria_backup: str = ""


def apply_plan(
    plan: IngestPlan,
    config: Config,
    storage: Storage,
    replace_criteria: bool = False,
) -> IngestOutcome:
    """Write the plan into THIS config's workspace — the only writer here.

    Every capture goes through the same application function the
    conversational path uses, with `via_form` set: same validation, same
    RFC-028 supersession, same evidence discipline, one extra fact
    recorded. A second write path would be free to disagree with those
    rules the first time either changed.
    """
    from wingman.application.interview import capture_interview_reaction
    from wingman.application.job_scoring import CRITERIA_FILENAME, criteria_path, save_criteria
    from wingman.application.qa_capture import capture_qa

    outcome = IngestOutcome()
    for capture in plan.captures:
        try:
            if capture.subtype:
                report = capture_interview_reaction(
                    capture.subtype,
                    capture.target,
                    capture.why,
                    config,
                    storage,
                    primary_purpose=capture.primary_purpose or None,
                    via_form=True,
                )
                outcome.written.append(f"{capture.subtype}: {capture.target} — {report.outcome}")
            else:
                qa = capture_qa(
                    capture.title,
                    capture.answer,
                    config,
                    storage,
                    destination=capture.destination,
                    via_form=True,
                )
                where = "answer bank" if capture.destination == "answers" else "profile"
                outcome.written.append(f"{where}: {capture.title} — {qa.outcome}")
        except IngestError as exc:
            outcome.failed.append(
                SkippedAnswer(
                    what=f"{capture.subtype or capture.destination}: "
                    f"{capture.target or capture.title}",
                    reason=str(exc),
                )
            )
    if plan.criteria_document:
        path = criteria_path(config)
        existing = path.read_text(encoding="utf-8") if path.exists() else ""
        if existing.strip() and not replace_criteria:
            # The document may have been refined in conversation since —
            # RFC-035's whole point is that it is the person's confirmed
            # wording. Overwriting it on the strength of a form answer, in
            # somebody else's workspace, is not a call this command gets to
            # make silently.
            outcome.failed.append(
                SkippedAnswer(
                    what=CRITERIA_FILENAME,
                    reason="a criteria document already exists and was NOT replaced — "
                    "re-run with --replace-criteria to overwrite it (the current text "
                    "is kept alongside it first)",
                )
            )
        else:
            if existing.strip():
                stamp = datetime.now(UTC).strftime("%Y%m%dT%H%M%S")
                backup = path.with_name(f"{path.stem}.replaced-{stamp}{path.suffix}")
                backup.write_text(existing, encoding="utf-8")
                outcome.criteria_backup = str(backup)
            save_criteria(config, plan.criteria_document)
            outcome.criteria_path = str(path)
    _logger.info(
        "form ingest slug=%s written=%d failed=%d criteria=%s",
        plan.slug,
        len(outcome.written),
        len(outcome.failed),
        bool(outcome.criteria_path),
    )
    return outcome


# The conversational path asks for these; a form does not. Named here and
# printed on every run rather than defaulted to something, because a
# default would be wingman's guess at how strongly somebody feels, filed
# on their behalf under a field built to hold their own answer.
UNASKED_FIELDS = (
    "intensity (RFC-050: mild / moderate / strong)",
    "company_reason (RFC-050: company / product / industry)",
    "value statement (RFC-057: what the nomination says they value)",
)


def render_plan(plan: IngestPlan, workspace: Path, criteria_exists: bool) -> str:
    """The preview: what will be captured, where, and into whose workspace.

    Shown in full before anything is written — including the assembled
    criteria document, because it is the one artefact here that no capture
    function will validate afterwards and the one most likely to be wrong
    in a way only a human notices.
    """
    lines = [
        f"Ingest an interview form into {plan.slug}'s workspace.",
        "",
        f"  tenant:     {plan.slug}",
        f"  workspace:  {workspace}",
        f"  responses:  {plan.source}",
    ]
    which = f"{plan.submission_index} of {plan.submission_count}"
    when = f", submitted {plan.submitted_at}" if plan.submitted_at else ""
    lines.append(f"  submission: {which}{when}")
    lines.append("")
    if plan.criteria_document:
        answered = len(plan.criteria_areas)
        lines.append(
            f"Job criteria (RFC-035) — {answered} answered area(s) become ONE document, "
            "job-criteria.md:"
        )
        lines.append("  ---")
        lines += [f"  {line}" if line else "  " for line in plan.criteria_document.splitlines()]
        lines.append("  ---")
        if criteria_exists:
            lines.append(
                "  A criteria document ALREADY EXISTS here. It is not replaced unless you "
                "pass --replace-criteria; the current text is kept alongside it first."
            )
        lines.append("")
    nominations = [capture for capture in plan.captures if capture.subtype]
    if nominations:
        lines.append("Profile captures (interview nominations — 'why' is the evidence quote):")
        for capture in nominations:
            lines.append(f"  {capture.subtype}: {capture.target}")
            lines.append(f'      why: "{capture.why}"')
            if capture.primary_purpose:
                lines.append(f'      understood purpose: "{capture.primary_purpose}"')
        lines.append("")
    for destination, heading in (
        ("profile", "Profile Q&A (question and answer, verbatim):"),
        ("answers", "Answer bank (RFC-030):"),
    ):
        entries = [
            capture
            for capture in plan.captures
            if not capture.subtype and capture.destination == destination
        ]
        if not entries:
            continue
        lines.append(heading)
        for capture in entries:
            lines.append(f"  {capture.title}")
            lines.append(f'      "{capture.answer}"')
        lines.append("")
    if plan.skipped:
        lines.append("Not captured:")
        for item in plan.skipped:
            lines.append(f"  {item.what} — {item.reason}")
        lines.append("")
    lines.append(f"Every capture records that it arrived via {FORM_ARRIVAL},")
    lines.append("so it stays distinguishable from an answer given in conversation.")
    lines.append("The form does not ask for, and nothing here sets: " + UNASKED_FIELDS[0] + ",")
    lines.append(f"{UNASKED_FIELDS[1]}, {UNASKED_FIELDS[2]}.")
    lines.append("They stay unset — the fields are optional by design — and can be added")
    lines.append("later in conversation.")
    return "\n".join(lines)


def render_outcome(outcome: IngestOutcome, slug: str) -> str:
    lines: list[str] = []
    if outcome.written:
        lines.append(f"Written into {slug}'s workspace:")
        lines += [f"  {line}" for line in outcome.written]
    if outcome.criteria_path:
        lines.append(f"  job criteria: {outcome.criteria_path}")
    if outcome.criteria_backup:
        lines.append(f"  previous criteria kept at: {outcome.criteria_backup}")
    if outcome.failed:
        lines.append("Not written:")
        lines += [f"  {item.what} — {item.reason}" for item in outcome.failed]
    if not lines:
        lines.append(f"Nothing was written into {slug}'s workspace.")
    return "\n".join(lines)
