#!/usr/bin/env python3
"""Generate the searchable RFC index without changing the stable RFC ledger."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LEDGER = ROOT / "docs" / "RFC.md"
INDEX = ROOT / "docs" / "RFC-INDEX.md"
HEADING = re.compile(r"^## (RFC-\d+): (.+)$", re.MULTILINE)


def anchor(title: str) -> str:
    """Match GitHub's heading-anchor normalization for this ledger's titles."""
    value = title.lower().replace("+", "").replace("`", "")
    value = re.sub(r"[^\w\s-]", "", value, flags=re.UNICODE)
    return re.sub(r"\s+", "-", value)


def render(ledger: str) -> str:
    rows = [
        "# Wingman RFC index",
        "",
        "Generated by `scripts/generate_rfc_index.py` from the stable, single-file",
        "[decision ledger](RFC.md). Run the generator after adding or renaming an RFC.",
        "Keeping the ledger intact preserves existing links and anchors.",
        "",
        "| RFC | Decision |",
        "|---|---|",
    ]
    for number, title in HEADING.findall(ledger):
        full = f"{number}: {title}"
        rows.append(f"| [{number}](RFC.md#{anchor(full)}) | {title} |")
    return "\n".join(rows) + "\n"


def main() -> None:
    INDEX.write_text(render(LEDGER.read_text(encoding="utf-8")), encoding="utf-8")


if __name__ == "__main__":
    main()
