#!/usr/bin/env python3
"""Regenerate src/wingman/changelog_data.py from this checkout's git history.

Run by hand before a release (docs/RELEASES.md) — NOT invoked at runtime.
See RFC-038 / src/wingman/domain/changelog.py: the running server cannot
rely on live git access (`uv tool install` never leaves a `.git` directory
behind, verified against a real installed instance — true even for the
"install from a local checkout" path, since it builds and installs a
wheel), so this script bakes merged-PR titles into a static, committed data
module that ships as ordinary package source.

Walks `git log --first-parent` on the current branch: `--first-parent`
keeps exactly one entry per merged PR (the mainline commit) and skips the
individual feature-branch commits a merge or squash absorbs. Two GitHub
merge shapes both appear in this repo's history and are both handled:

  - squash merge: subject ends in " (#123)" -> title is everything before it
  - true merge commit: subject is "Merge pull request #123 from ..." -> the
    PR title is the commit body's first line (GitHub's own convention)

Commits matching neither (a handful of very early direct-to-main commits,
from before this repo settled on a PR-per-slice workflow) are skipped:
they carry no PR number, so there is no merged PR to cite.

Also stamps GENERATED_AT_COMMIT (this checkout's HEAD, full sha) and
GENERATED_AT_DATE into the output. Issue #202: those two fields let the
domain layer prove, at call time, whether the running build's own commit
(src/wingman/version.py, hatch-vcs) has moved past the commit this file was
generated from — the release-gate half of the fix, alongside the
tests/unit/test_changelog.py regression test that fails a local `pytest -q`
run (per house convention, before opening a PR) whenever a merged PR landed
after this file's newest entry and was never accounted for.

Usage: python scripts/generate_changelog.py
"""

from __future__ import annotations

import re
import subprocess
from datetime import UTC, datetime
from pathlib import Path

_SQUASH_RE = re.compile(r"^(.*) \(#(\d+)\)$")
_MERGE_RE = re.compile(r"^Merge pull request #(\d+) from")

_REPO_ROOT = Path(__file__).resolve().parents[1]
_OUTPUT = _REPO_ROOT / "src" / "wingman" / "changelog_data.py"

# Record separator \x1e / field separator \x1f: both are control bytes that
# never appear in a commit message, so splitting is unambiguous even when
# a PR body itself contains blank lines or punctuation.
_LOG_FORMAT = "%H%x1f%cI%x1f%s%x1f%b%x1e"


def _entries() -> list[tuple[str, int, str]]:
    raw = subprocess.run(
        ["git", "log", "--first-parent", f"--format={_LOG_FORMAT}"],
        cwd=_REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    entries: list[tuple[str, int, str]] = []
    for record in raw.split("\x1e"):
        record = record.strip("\n")
        if not record:
            continue
        _sha, commit_date, subject, body = record.split("\x1f", 3)
        date = commit_date[:10]  # commit date's day, our PR-merge-date proxy
        squash = _SQUASH_RE.match(subject)
        if squash:
            entries.append((date, int(squash.group(2)), squash.group(1)))
            continue
        merge = _MERGE_RE.match(subject)
        if merge:
            body_lines = [line for line in body.strip().splitlines() if line.strip()]
            if body_lines:
                entries.append((date, int(merge.group(1)), body_lines[0].strip()))
            continue
    return entries


def _generation_commit() -> str:
    """Full sha of this checkout's HEAD, right now — the commit these
    entries were actually walked from (issue #202's staleness stamp)."""
    return subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=_REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()


def _render(
    entries: list[tuple[str, int, str]], generated_at_commit: str, generated_at_date: str
) -> str:
    rows = "\n".join(f"    ({date!r}, {pr}, {title!r})," for date, pr, title in entries)
    return (
        '"""Generated by scripts/generate_changelog.py — do not hand-edit (RFC-038).\n\n'
        "Regenerate before each release: `python scripts/generate_changelog.py`. Each\n"
        'row is (merge date "YYYY-MM-DD", PR number, PR title verbatim), newest\n'
        "first, derived from `git log --first-parent` on this checkout at generation\n"
        "time. See RFC-038 and src/wingman/domain/changelog.py for why this is a\n"
        "committed static file rather than a live git read.\n\n"
        "GENERATED_AT_COMMIT/GENERATED_AT_DATE are this checkout's own HEAD at the\n"
        "moment this file was written (issue #202). The domain layer compares\n"
        "GENERATED_AT_COMMIT against the running build's own commit stamp\n"
        "(src/wingman/version.py, hatch-vcs) to prove — not guess — whether this\n"
        "data has drifted behind the code it ships with, instead of reporting a\n"
        "confident zero it hasn't verified.\n"
        '"""\n\n'
        "from __future__ import annotations\n\n"
        f"GENERATED_AT_COMMIT = {generated_at_commit!r}\n"
        f"GENERATED_AT_DATE = {generated_at_date!r}\n\n"
        "CHANGELOG_DATA: tuple[tuple[str, int, str], ...] = (\n"
        f"{rows}\n"
        ")\n"
    )


def main() -> None:
    entries = _entries()
    generated_at_commit = _generation_commit()
    generated_at_date = datetime.now(UTC).date().isoformat()
    _OUTPUT.write_text(_render(entries, generated_at_commit, generated_at_date), encoding="utf-8")
    # Long titles need Black-style wrapping to respect the repo's line length;
    # `ruff format` is the same tool the rest of the codebase is formatted with.
    subprocess.run(["ruff", "format", str(_OUTPUT)], cwd=_REPO_ROOT, check=False)
    print(
        f"Wrote {len(entries)} entries to {_OUTPUT.relative_to(_REPO_ROOT)} "
        f"(HEAD {generated_at_commit[:12]}, {generated_at_date})"
    )


if __name__ == "__main__":
    main()
