"""Generated by scripts/generate_changelog.py — do not hand-edit (RFC-038).

Regenerate before each release: `python scripts/generate_changelog.py`. Each
row is (merge date "YYYY-MM-DD", PR number, PR title verbatim), newest
first, derived from `git log --first-parent` on this checkout at generation
time. See RFC-038 and src/wingman/domain/changelog.py for why this is a
committed static file rather than a live git read.
"""

from __future__ import annotations

CHANGELOG_DATA: tuple[tuple[str, int, str], ...] = (
    ("2026-07-23", 140, "Add Claude Desktop walkthroughs: local install and remote (Lobster)"),
    ("2026-07-23", 139, "Remove dormant project-scoped wingman MCP entry from .mcp.json"),
    ("2026-07-22", 132, "Admin page: fix self-check deadlock and off-box launcher links"),
    ("2026-07-22", 131, "Tunnel-port support + admin installations page (#128, #130)"),
    ("2026-07-22", 129, "web UI: fix Connect tab rendering nothing when selected"),
    ("2026-07-22", 127, "web UI: Connect tab with the MCP connector URL (#126)"),
    ("2026-07-22", 123, "wingman mcp url: print connector URLs without grepping the banner (#122)"),
    ("2026-07-22", 121, "CLAUDE.md: deployment facts — lobster's ~/src convention, Mac paths"),
    ("2026-07-22", 120, "wingman-ctl cycle: stop / upgrade / start in one act"),
    (
        "2026-07-22",
        119,
        "Web UI revised redesign: desktop tabs, shared token block, capped groups (#118)",
    ),
    (
        "2026-07-22",
        114,
        "RFC-037: relationship objectives — thesis per person, tickler, log, review",
    ),
    (
        "2026-07-22",
        112,
        "RFC-036: Q&A capture as profile evidence, and recall before asking (#96, #98)",
    ),
    ("2026-07-22", 111, "One JSON extractor for every agent; reject error-page redirects (#97)"),
    ("2026-07-21", 110, "Action-list evidence links carry page titles (#109)"),
    (
        "2026-07-21",
        108,
        "Flush the startup banner: wg start/status URL echo was grepping an empty log",
    ),
    (
        "2026-07-21",
        107,
        "Criteria interview loop: one question set for seeding AND periodic review",
    ),
    (
        "2026-07-21",
        106,
        "RFC-035 implementation: scored openings in the digest, driven by job-criteria.md",
    ),
    (
        "2026-07-21",
        105,
        "RFC-035: job interest scoring — embedding recall, criteria doc, judged brief",
    ),
    ("2026-07-21", 104, "Emit tunnel URLs at startup; see and stop orphaned HTTP servers"),
    ("2026-07-21", 101, "Accept the tunnel's Host header over --http (#100)"),
    (
        "2026-07-21",
        99,
        "Web UI home: three states, humanized artifacts, Electric Cobalt system (#95)",
    ),
    ("2026-07-21", 93, "Add .mcp.json: wingman as a native MCP server in Claude Code sessions"),
    (
        "2026-07-20",
        92,
        "Native path prefixes: the server itself listens on /trent, /dhk (--prefix)",
    ),
    (
        "2026-07-20",
        91,
        "Web UI works behind path mounts: relative URLs + relative canonical redirect",
    ),
    (
        "2026-07-20",
        90,
        "Validated key intake: workspace key file + web form that tests before storing (RFC-034)",
    ),
    ("2026-07-20", 89, "The read surface: a small web UI for glancing and files (RFC-033)"),
    ("2026-07-20", 88, "docs: multi-instance design — one person, one workspace, N instances"),
    ("2026-07-20", 87, "Digest links: markdown [title](url) instead of raw URL dumps"),
    ("2026-07-20", 86, "Pretty digest: a styled HTML twin written beside the markdown"),
    (
        "2026-07-20",
        85,
        "Server process management: wingman mcp status/stop + wingman-ctl (RFC-032)",
    ),
    ("2026-07-19", 84, "docs: release notes for v0.3.0 and v0.4.0 (docs/RELEASES.md)"),
    ("2026-07-19", 83, "Digest action triage: mute/snooze verdicts stop the roll-over (RFC-031)"),
    (
        "2026-07-19",
        82,
        "Add the application answer bank: refined Q+A+context, reused across applications (RFC-030)",
    ),
    (
        "2026-07-19",
        79,
        "Company-attached feeds: follow a company blog with no person needed (RFC-029)",
    ),
    ("2026-07-19", 78, "docs: SERVER.md — wingman on an always-on Ubuntu server"),
    (
        "2026-07-19",
        77,
        "Document lineage: a new version of a document supersedes its own claims (RFC-028)",
    ),
    ("2026-07-19", 76, "Add career-profile management: list, rm, resolve, clear (RFC-027)"),
    (
        "2026-07-19",
        74,
        "docs: record the multi-engine research council design; refresh ROADMAP to v0.3.0",
    ),
    (
        "2026-07-19",
        73,
        "Markdown-normalized extraction + whitespace-tolerant evidence gates (RFC-026)",
    ),
    ("2026-07-19", 72, "Remediate the external code review: fix all ten findings (#62–#71)"),
    (
        "2026-07-19",
        61,
        "docs: CLAUDE.md with the standing feature-request protocol and routing map",
    ),
    (
        "2026-07-19",
        60,
        "Add feature requests: conversational capture to GitHub issue, gated (RFC-025)",
    ),
    ("2026-07-19", 59, "Version surfacing: git-derived build stamp via hatch-vcs"),
    (
        "2026-07-19",
        58,
        "From hiring signal to application: assess --url and the application pack (RFC-024)",
    ),
    (
        "2026-07-19",
        57,
        "Digest surfacing: action list, wingman digest, latest.md, --out, searchable",
    ),
    ("2026-07-18", 56, "Add opt-in local usage telemetry with transcript harvesting (RFC-023)"),
    ("2026-07-18", 55, "Add unified search across every store, keyword plus semantic (RFC-022)"),
    (
        "2026-07-18",
        54,
        "docs: groom everything; add Install/Operations and Introduction/Walkthrough guides",
    ),
    ("2026-07-18", 51, "Add wingman keys: Keychain-backed API keys, hydrated at startup (RFC-019)"),
    ("2026-07-18", 50, "docs: research briefing — privacy/egress out of scope per user direction"),
    (
        "2026-07-18",
        49,
        "Add company follow + overnight: assembled focus, consented deep-refresh (RFC-018)",
    ),
    ("2026-07-18", 48, "docs: competitive research briefing + reordered backlog"),
    ("2026-07-18", 47, "docs: refresh session snapshot through PR #46 (backlog complete)"),
    ("2026-07-18", 46, "Add remote MCP: loopback HTTP behind a capability path (RFC-017)"),
    (
        "2026-07-18",
        45,
        "Add company pov: model-synthesized themes, validated quote-by-quote (RFC-016)",
    ),
    (
        "2026-07-18",
        44,
        "Add approved-source company research: user-named pages, deterministic diffs (RFC-015)",
    ),
    ("2026-07-18", 43, "Add wingman backup/restore: dated workspace tarballs with retention"),
    (
        "2026-07-18",
        42,
        "Relevance-filter news headlines: common-word companies need corporate context",
    ),
    (
        "2026-07-18",
        41,
        "docs: refresh session snapshot through PR #40 (miso, watchlists, 2x2 dock)",
    ),
    ("2026-07-18", 40, "Add make-it-so (alias miso) and watchlists that cycle it"),
    ("2026-07-18", 39, "Person export becomes a 2x2 briefing dock; add people news (RFC-014)"),
    ("2026-07-18", 38, "Smarter feed discovery: page anchors and site-root paths (still bounded)"),
    (
        "2026-07-18",
        37,
        "Printing the tabbed HTML person page collapses it into the three-column sheet",
    ),
    (
        "2026-07-18",
        36,
        "Add own-corpus POV, people docs listing, tabbed HTML export, empty-bullets hint",
    ),
    (
        "2026-07-18",
        35,
        "docs: record user environment in session snapshot (repos at ~/Documents/dev)",
    ),
    (
        "2026-07-18",
        34,
        "Densify the landscape person sheet; dedupe links; re-land npx render hints",
    ),
    ("2026-07-18", 33, "Outreach round: stance dimensions, purposes, intro bullets, export --out"),
    (
        "2026-07-18",
        32,
        "Enrich the person sheet's Related column: contact links, company, in-common, warmth",
    ),
    ("2026-07-18", 31, "Write the stylesheet's absolute path into export frontmatter"),
    (
        "2026-07-18",
        30,
        "Add print-ready exports: Letter-format artifacts styled by the site design system",
    ),
    (
        "2026-07-18",
        29,
        "Resume imports (PDF/DOCX/LaTeX/Google URLs), fetch hardening, partial-name UX",
    ),
    (
        "2026-07-18",
        28,
        "Fix embed batching: pack against Voyage's per-batch token cap, not just count",
    ),
    ("2026-07-17", 27, "docs: refresh session snapshot — queue complete through company dossiers"),
    (
        "2026-07-17",
        26,
        "Add company dossiers: dated, labeled snapshots from validated data (RFC-012)",
    ),
    (
        "2026-07-17",
        25,
        "Add outreach briefs: draft talking points connecting a person's POV to your writing",
    ),
    (
        "2026-07-17",
        24,
        "Add company similarity: rankings from people-by-company and org-attributed writing",
    ),
    ("2026-07-17", 23, "docs: session context snapshot for future-session resume"),
    ("2026-07-17", 22, "Add POV cards: evidence-backed summaries of what a person thinks"),
    ("2026-07-17", 21, "MCP server at full CLI parity; parity principle in RFC-008"),
    ("2026-07-17", 20, "Add 'wingman people discover': recommendations-graph suggestions"),
    ("2026-07-17", 19, "Add 'wingman sync': one-command fetch-and-embed with launchd recipe"),
    ("2026-07-17", 18, "General feeds: RSS/Atom autodiscovery and index-page sources, RFC-011"),
    ("2026-07-17", 17, "Add 'wingman demo': guided tour on real public data, isolated workspace"),
    ("2026-07-17", 16, "docs: SETUP.md — standing up your own instance, with graceful degradation"),
    ("2026-07-17", 15, "Semantic similarity: embeddings over people's writing and your corpus"),
    ("2026-07-17", 14, "People watchlist: connections seeding and public Substack feeds"),
    ("2026-07-17", 13, "docs: record DuckDB evaluation outcome in RFC-002"),
    ("2026-07-17", 12, "wingman-mcp: local MCP server exposing the workspace as tools (RFC-008)"),
    (
        "2026-07-17",
        11,
        "LinkedIn import: positions, skills, and recommendations as cited profile items",
    ),
    (
        "2026-07-17",
        10,
        "Corpus: use Substack's posts.csv manifest for real titles and publish dates",
    ),
    ("2026-07-17", 9, "Corpus: ingest your writing as citable evidence with full-text search"),
    ("2026-07-17", 8, "Phase 2 first slice: job description → cited fit brief"),
    (
        "2026-07-17",
        7,
        "Phase 1 first slice: resume → career.json / career.md with evidence citations",
    ),
    ("2026-07-17", 6, "Phase 0: provenance-aware storage and real init/doctor/status"),
    ("2026-07-16", 5, "Docs cleanup: deduplicate, MIT license, Claude build models, retire ADRs"),
    (
        "2026-07-15",
        4,
        "Design doc review: reconcile invariants, deepen DESIGN, consolidate model routing (supersedes #3)",
    ),
    ("2026-07-15", 2, "Add Phase 0 repository skeleton and core design document set"),
    ("2026-07-15", 1, "Add AGENTS.md with agent working instructions"),
)
